security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG

server:
  ssl:
    key-store: keystore.p12
    key-store-password: password
    keyStoreType: PKCS12
    keyAlias: test

eureka:
  instance:
    hostname: localhost
    secure-port-enabled: true
    nonSecurePortEnabled: false
    #homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    #statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    #healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    
